wandb_version: 1

learning_rate:
  desc: null
  value: 0.0001
architecture:
  desc: null
  value: DENSENET-169
dataset:
  desc: null
  value: Chest X-Ray Images (Pneumonia)
class_names:
  desc: null
  value:
  - normal
  - bacteria
  - virus
num_classes:
  desc: null
  value: 3
val_split:
  desc: null
  value: 0.2
init_epochs:
  desc: null
  value: 10
fine_epochs:
  desc: null
  value: 30
batch_size:
  desc: null
  value: 32
image_size:
  desc: null
  value:
  - 300
  - 300
dropout_rate:
  desc: null
  value: 0.2
activation:
  desc: null
  value: softmax
_wandb:
  desc: null
  value:
    python_version: 3.8.0
    cli_version: 0.15.5
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1689776955.906999
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 7
      - 13
      - 16
      - 23
      - 38
      4: 3.8.0
      5: 0.15.5
      8:
      - 1
      - 3
      - 5
    m:
    - 1: epoch/epoch
      6:
      - 3
    - 1: epoch/loss
      5: 1
      6:
      - 1
    - 1: epoch/accuracy
      5: 1
      6:
      - 1
    - 1: epoch/val_loss
      5: 1
      6:
      - 1
    - 1: epoch/val_accuracy
      5: 1
      6:
      - 1
    - 1: epoch/learning_rate
      5: 1
      6:
      - 1
